// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: iov/escrow/v1beta1/types.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EscrowState defines the state of an escrow
type EscrowState int32

const (
	// ESCROW_STATE_OPEN defines an open state.
	EscrowState_Open EscrowState = 0
	// ESCROW_STATE_COMPLETED defines a completed state.
	EscrowState_Completed EscrowState = 1
	// ESCROW_STATE_REFUNDED defines a refunded state.
	EscrowState_Refunded EscrowState = 2
	// ESCROW_STATE_REFUNDED defines an expired state.
	EscrowState_Expired EscrowState = 3
)

var EscrowState_name = map[int32]string{
	0: "ESCROW_STATE_OPEN",
	1: "ESCROW_STATE_COMPLETED",
	2: "ESCROW_STATE_REFUNDED",
	3: "ESCROW_STATE_EXPIRED",
}

var EscrowState_value = map[string]int32{
	"ESCROW_STATE_OPEN":      0,
	"ESCROW_STATE_COMPLETED": 1,
	"ESCROW_STATE_REFUNDED":  2,
	"ESCROW_STATE_EXPIRED":   3,
}

func (x EscrowState) String() string {
	return proto.EnumName(EscrowState_name, int32(x))
}

func (EscrowState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_06970306f8aa7966, []int{0}
}

// Escrow defines the struct of an escrow
type Escrow struct {
	Id       string                                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Seller   string                                   `protobuf:"bytes,2,opt,name=seller,proto3" json:"seller,omitempty"`
	Object   *types.Any                               `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Price    github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=price,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"price"`
	State    EscrowState                              `protobuf:"varint,5,opt,name=state,proto3,enum=starnamed.x.escrow.v1beta1.EscrowState" json:"state,omitempty"`
	Deadline uint64                                   `protobuf:"varint,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

func (m *Escrow) Reset()         { *m = Escrow{} }
func (m *Escrow) String() string { return proto.CompactTextString(m) }
func (*Escrow) ProtoMessage()    {}
func (*Escrow) Descriptor() ([]byte, []int) {
	return fileDescriptor_06970306f8aa7966, []int{0}
}
func (m *Escrow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Escrow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Escrow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Escrow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Escrow.Merge(m, src)
}
func (m *Escrow) XXX_Size() int {
	return m.Size()
}
func (m *Escrow) XXX_DiscardUnknown() {
	xxx_messageInfo_Escrow.DiscardUnknown(m)
}

var xxx_messageInfo_Escrow proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("starnamed.x.escrow.v1beta1.EscrowState", EscrowState_name, EscrowState_value)
	proto.RegisterType((*Escrow)(nil), "starnamed.x.escrow.v1beta1.Escrow")
}

func init() { proto.RegisterFile("iov/escrow/v1beta1/types.proto", fileDescriptor_06970306f8aa7966) }

var fileDescriptor_06970306f8aa7966 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x8e, 0xd2, 0x50,
	0x14, 0xc7, 0x5b, 0xbe, 0x64, 0x2e, 0x3a, 0xc1, 0x1b, 0x24, 0x9d, 0x2e, 0x4a, 0x63, 0x62, 0xa6,
	0x6a, 0xb8, 0x75, 0x70, 0xed, 0x62, 0x80, 0x6b, 0x32, 0x89, 0x0e, 0xa4, 0x60, 0x34, 0x6e, 0x48,
	0x3f, 0x0e, 0x58, 0x2d, 0xbd, 0x4d, 0x6f, 0x41, 0x78, 0x03, 0xc3, 0xca, 0x17, 0x60, 0xe5, 0xce,
	0x8d, 0x9b, 0x79, 0x08, 0xe2, 0x6a, 0x96, 0xae, 0xfc, 0x80, 0x17, 0x31, 0xb4, 0x85, 0x0c, 0x8b,
	0x59, 0xf5, 0xfe, 0xef, 0xf9, 0xff, 0xce, 0xe9, 0xf9, 0xb7, 0x48, 0x71, 0xd9, 0x54, 0x07, 0x6e,
	0x87, 0xec, 0xb3, 0x3e, 0x3d, 0xb3, 0x20, 0x32, 0xcf, 0xf4, 0x68, 0x1e, 0x00, 0x27, 0x41, 0xc8,
	0x22, 0x86, 0x65, 0x1e, 0x99, 0xa1, 0x6f, 0x8e, 0xc1, 0x21, 0x33, 0x92, 0xf8, 0x48, 0xea, 0x93,
	0x15, 0x9b, 0xf1, 0x31, 0xe3, 0xba, 0x65, 0x72, 0xd8, 0xc3, 0x36, 0x73, 0xfd, 0x84, 0x95, 0x2b,
	0x23, 0x36, 0x62, 0xf1, 0x51, 0xdf, 0x9e, 0xd2, 0xdb, 0x93, 0x11, 0x63, 0x23, 0x0f, 0xf4, 0x58,
	0x59, 0x93, 0xa1, 0x6e, 0xfa, 0xf3, 0x5d, 0x29, 0x69, 0x38, 0x48, 0x98, 0x44, 0x24, 0xa5, 0x87,
	0x57, 0x19, 0x54, 0xa0, 0xf1, 0x78, 0x7c, 0x8c, 0x32, 0xae, 0x23, 0x89, 0xaa, 0xa8, 0x1d, 0x19,
	0x19, 0xd7, 0xc1, 0x55, 0x54, 0xe0, 0xe0, 0x79, 0x10, 0x4a, 0x99, 0xf8, 0x2e, 0x55, 0xb8, 0x8d,
	0x0a, 0xcc, 0xfa, 0x08, 0x76, 0x24, 0x65, 0x55, 0x51, 0x2b, 0x35, 0x2a, 0x24, 0x99, 0x4c, 0x76,
	0x93, 0xc9, 0xb9, 0x3f, 0x6f, 0x56, 0x7f, 0x5e, 0xd5, 0x71, 0x3f, 0x34, 0x7d, 0x3e, 0x84, 0xd0,
	0xb4, 0x3c, 0xe8, 0xc4, 0x8c, 0x91, 0xb2, 0xd8, 0x44, 0xf9, 0x20, 0x74, 0x6d, 0x90, 0x72, 0x6a,
	0x56, 0x2b, 0x35, 0x4e, 0x48, 0xfa, 0x5a, 0xdb, 0xa5, 0x77, 0x49, 0x90, 0x16, 0x73, 0xfd, 0xe6,
	0xb3, 0xd5, 0xef, 0x9a, 0xf0, 0xfd, 0x4f, 0x4d, 0x1b, 0xb9, 0xd1, 0x87, 0x89, 0x45, 0x6c, 0x36,
	0x4e, 0x77, 0x48, 0x1f, 0x75, 0xee, 0x7c, 0x4a, 0xc3, 0xdd, 0x02, 0xdc, 0x48, 0x3a, 0xe3, 0x17,
	0x28, 0xcf, 0x23, 0x33, 0x02, 0x29, 0xaf, 0x8a, 0xda, 0x71, 0xe3, 0x94, 0xdc, 0x9e, 0x39, 0x49,
	0x32, 0xe8, 0x6d, 0xed, 0x46, 0x42, 0x61, 0x19, 0x15, 0x1d, 0x30, 0x1d, 0xcf, 0xf5, 0x41, 0x2a,
	0xa8, 0xa2, 0x96, 0x33, 0xf6, 0xfa, 0xc9, 0x0f, 0x11, 0x95, 0x6e, 0x20, 0xb8, 0x86, 0xee, 0xd3,
	0x5e, 0xcb, 0xe8, 0xbc, 0x1d, 0xf4, 0xfa, 0xe7, 0x7d, 0x3a, 0xe8, 0x74, 0xe9, 0x65, 0x59, 0x90,
	0x8b, 0x8b, 0xa5, 0x9a, 0xeb, 0x04, 0xe0, 0xe3, 0xc7, 0xa8, 0x7a, 0x60, 0x68, 0x75, 0x5e, 0x77,
	0x5f, 0xd1, 0x3e, 0x6d, 0x97, 0x45, 0xf9, 0xde, 0x62, 0xa9, 0x1e, 0xb5, 0xd8, 0x38, 0xf0, 0x20,
	0x02, 0x07, 0x9f, 0xa2, 0x07, 0x07, 0x56, 0x83, 0xbe, 0x7c, 0x73, 0xd9, 0xa6, 0xed, 0x72, 0x46,
	0xbe, 0xbb, 0x58, 0xaa, 0x45, 0x03, 0x86, 0x13, 0xdf, 0x01, 0x07, 0x3f, 0x42, 0x95, 0x03, 0x23,
	0x7d, 0xd7, 0xbd, 0x30, 0x68, 0xbb, 0x9c, 0x95, 0x4b, 0x8b, 0xa5, 0x7a, 0x87, 0xce, 0x02, 0x37,
	0x04, 0x47, 0xce, 0x7d, 0xf9, 0xa6, 0x88, 0xcd, 0x8b, 0xd5, 0x3f, 0x45, 0x58, 0xad, 0x15, 0xf1,
	0x7a, 0xad, 0x88, 0x7f, 0xd7, 0x8a, 0xf8, 0x75, 0xa3, 0x08, 0xd7, 0x1b, 0x45, 0xf8, 0xb5, 0x51,
	0x84, 0xf7, 0x4f, 0x6f, 0x64, 0xeb, 0xb2, 0x69, 0x9d, 0xf9, 0xa0, 0xef, 0xd3, 0xd2, 0x67, 0xbb,
	0x3f, 0x39, 0x0e, 0xd9, 0x2a, 0xc4, 0x1f, 0xfa, 0xf9, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20,
	0xe4, 0xa8, 0xa9, 0xe4, 0x02, 0x00, 0x00,
}

func (m *Escrow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Escrow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Escrow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Deadline != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Deadline))
		i--
		dAtA[i] = 0x30
	}
	if m.State != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Price) > 0 {
		for iNdEx := len(m.Price) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Price[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Object != nil {
		{
			size, err := m.Object.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Seller) > 0 {
		i -= len(m.Seller)
		copy(dAtA[i:], m.Seller)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Seller)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Escrow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Seller)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Object != nil {
		l = m.Object.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Price) > 0 {
		for _, e := range m.Price {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.State != 0 {
		n += 1 + sovTypes(uint64(m.State))
	}
	if m.Deadline != 0 {
		n += 1 + sovTypes(uint64(m.Deadline))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Escrow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Escrow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Escrow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Object", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Object == nil {
				m.Object = &types.Any{}
			}
			if err := m.Object.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = append(m.Price, types1.Coin{})
			if err := m.Price[len(m.Price)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= EscrowState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			m.Deadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deadline |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
