// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: x/starname/types/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryDomainRequest is the request type for the Query/Domain RPC method.
type QueryDomainRequest struct {
	// Name is the name of the domain.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`
}

func (m *QueryDomainRequest) Reset()         { *m = QueryDomainRequest{} }
func (m *QueryDomainRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDomainRequest) ProtoMessage()    {}
func (*QueryDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7e34c330677649, []int{0}
}
func (m *QueryDomainRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDomainRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDomainRequest.Merge(m, src)
}
func (m *QueryDomainRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDomainRequest proto.InternalMessageInfo

// QueryDomainResponse is the response type for the Query/Domain RPC method.
type QueryDomainResponse struct {
	// Domain is the information associated with the domain.
	Domain *Domain `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty" yaml:"domain"`
}

func (m *QueryDomainResponse) Reset()         { *m = QueryDomainResponse{} }
func (m *QueryDomainResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDomainResponse) ProtoMessage()    {}
func (*QueryDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7e34c330677649, []int{1}
}
func (m *QueryDomainResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDomainResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDomainResponse.Merge(m, src)
}
func (m *QueryDomainResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDomainResponse proto.InternalMessageInfo

// QueryDomainAccountsRequest is the request type for the Query/DomainAccounts RPC method.
type QueryDomainAccountsRequest struct {
	// Domain is the name of the domain.
	Domain     string             `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty" yaml:"domain"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDomainAccountsRequest) Reset()         { *m = QueryDomainAccountsRequest{} }
func (m *QueryDomainAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDomainAccountsRequest) ProtoMessage()    {}
func (*QueryDomainAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7e34c330677649, []int{2}
}
func (m *QueryDomainAccountsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDomainAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDomainAccountsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDomainAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDomainAccountsRequest.Merge(m, src)
}
func (m *QueryDomainAccountsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDomainAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDomainAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDomainAccountsRequest proto.InternalMessageInfo

// QueryDomainAccountsResponse is the response type for the Query/DomainAccounts RPC method.
type QueryDomainAccountsResponse struct {
	// Accounts is the accounts associated with the domain.
	Accounts []*Account          `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty" yaml:"accounts"`
	Page     *query.PageResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (m *QueryDomainAccountsResponse) Reset()         { *m = QueryDomainAccountsResponse{} }
func (m *QueryDomainAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDomainAccountsResponse) ProtoMessage()    {}
func (*QueryDomainAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7e34c330677649, []int{3}
}
func (m *QueryDomainAccountsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDomainAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDomainAccountsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDomainAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDomainAccountsResponse.Merge(m, src)
}
func (m *QueryDomainAccountsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDomainAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDomainAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDomainAccountsResponse proto.InternalMessageInfo

// QueryStarnameRequest is the request type for the Query/Starname RPC method.
type QueryStarnameRequest struct {
	// Starname is the of the form account*domain.
	Starname string `protobuf:"bytes,1,opt,name=starname,proto3" json:"starname,omitempty" yaml:"starname"`
}

func (m *QueryStarnameRequest) Reset()         { *m = QueryStarnameRequest{} }
func (m *QueryStarnameRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStarnameRequest) ProtoMessage()    {}
func (*QueryStarnameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7e34c330677649, []int{4}
}
func (m *QueryStarnameRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStarnameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStarnameRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStarnameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStarnameRequest.Merge(m, src)
}
func (m *QueryStarnameRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryStarnameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStarnameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStarnameRequest proto.InternalMessageInfo

// QueryStarnameResponse is the response type for the Query/Starname RPC method.
type QueryStarnameResponse struct {
	// Account is the information associated with the starname.
	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty" yaml:"account"`
}

func (m *QueryStarnameResponse) Reset()         { *m = QueryStarnameResponse{} }
func (m *QueryStarnameResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStarnameResponse) ProtoMessage()    {}
func (*QueryStarnameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7e34c330677649, []int{5}
}
func (m *QueryStarnameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStarnameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStarnameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStarnameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStarnameResponse.Merge(m, src)
}
func (m *QueryStarnameResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStarnameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStarnameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStarnameResponse proto.InternalMessageInfo

// QueryOwnerAccountsRequest is the request type for the Query/OwnerAccounts RPC method.
type QueryOwnerAccountsRequest struct {
	// Owner is the owner of accounts.
	Owner      string             `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryOwnerAccountsRequest) Reset()         { *m = QueryOwnerAccountsRequest{} }
func (m *QueryOwnerAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOwnerAccountsRequest) ProtoMessage()    {}
func (*QueryOwnerAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7e34c330677649, []int{6}
}
func (m *QueryOwnerAccountsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOwnerAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOwnerAccountsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOwnerAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOwnerAccountsRequest.Merge(m, src)
}
func (m *QueryOwnerAccountsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOwnerAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOwnerAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOwnerAccountsRequest proto.InternalMessageInfo

// QueryOwnerAccountsResponse is the response type for the Query/OwnerAccounts RPC method.
type QueryOwnerAccountsResponse struct {
	// Accounts is the accounts associated with owner.
	Accounts []*Account          `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty" yaml:"accounts"`
	Page     *query.PageResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (m *QueryOwnerAccountsResponse) Reset()         { *m = QueryOwnerAccountsResponse{} }
func (m *QueryOwnerAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOwnerAccountsResponse) ProtoMessage()    {}
func (*QueryOwnerAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7e34c330677649, []int{7}
}
func (m *QueryOwnerAccountsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOwnerAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOwnerAccountsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOwnerAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOwnerAccountsResponse.Merge(m, src)
}
func (m *QueryOwnerAccountsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOwnerAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOwnerAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOwnerAccountsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryDomainRequest)(nil), "starnamed.x.starname.v1beta1.QueryDomainRequest")
	proto.RegisterType((*QueryDomainResponse)(nil), "starnamed.x.starname.v1beta1.QueryDomainResponse")
	proto.RegisterType((*QueryDomainAccountsRequest)(nil), "starnamed.x.starname.v1beta1.QueryDomainAccountsRequest")
	proto.RegisterType((*QueryDomainAccountsResponse)(nil), "starnamed.x.starname.v1beta1.QueryDomainAccountsResponse")
	proto.RegisterType((*QueryStarnameRequest)(nil), "starnamed.x.starname.v1beta1.QueryStarnameRequest")
	proto.RegisterType((*QueryStarnameResponse)(nil), "starnamed.x.starname.v1beta1.QueryStarnameResponse")
	proto.RegisterType((*QueryOwnerAccountsRequest)(nil), "starnamed.x.starname.v1beta1.QueryOwnerAccountsRequest")
	proto.RegisterType((*QueryOwnerAccountsResponse)(nil), "starnamed.x.starname.v1beta1.QueryOwnerAccountsResponse")
}

func init() { proto.RegisterFile("x/starname/types/query.proto", fileDescriptor_da7e34c330677649) }

var fileDescriptor_da7e34c330677649 = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0x4f, 0x4f, 0x13, 0x4f,
	0x18, 0xc7, 0x3b, 0xfc, 0x80, 0x1f, 0x0c, 0x02, 0x3a, 0x60, 0x82, 0x6b, 0xb3, 0x8b, 0x23, 0x02,
	0x12, 0xd9, 0x81, 0x72, 0x10, 0xf4, 0x64, 0x63, 0xf4, 0x88, 0x2e, 0x89, 0x07, 0x6f, 0xd3, 0x32,
	0xae, 0x9b, 0xb4, 0x3b, 0x4b, 0x77, 0x8b, 0x34, 0x4d, 0x2f, 0x5e, 0x3d, 0x68, 0x62, 0x62, 0xe2,
	0x3b, 0xf0, 0x66, 0x34, 0x5e, 0x7c, 0x07, 0x1c, 0x49, 0xbc, 0x78, 0x6a, 0xb4, 0xf5, 0x15, 0xf4,
	0x15, 0x98, 0x9d, 0x3f, 0xa5, 0xdd, 0x62, 0x6d, 0x8d, 0x07, 0x2f, 0xcd, 0xf6, 0x99, 0x79, 0xbe,
	0xdf, 0xcf, 0x3c, 0xcf, 0x3c, 0xbb, 0x30, 0x7d, 0x44, 0xc2, 0x88, 0x96, 0x7c, 0x5a, 0x64, 0x24,
	0xaa, 0x04, 0x2c, 0x24, 0x07, 0x65, 0x56, 0xaa, 0xd8, 0x41, 0x89, 0x47, 0x1c, 0xa5, 0xf5, 0xda,
	0xbe, 0x7d, 0x64, 0xeb, 0x67, 0xfb, 0x70, 0x33, 0xc7, 0x22, 0xba, 0x69, 0xcc, 0xbb, 0xdc, 0xe5,
	0x62, 0x23, 0x89, 0x9f, 0x64, 0x8e, 0x91, 0x76, 0x39, 0x77, 0x0b, 0x8c, 0xd0, 0xc0, 0x23, 0xd4,
	0xf7, 0x79, 0x44, 0x23, 0x8f, 0xfb, 0xa1, 0x5e, 0xed, 0xf1, 0x13, 0xbf, 0x6a, 0x75, 0x2d, 0xcf,
	0xc3, 0x22, 0x0f, 0x49, 0x8e, 0x86, 0x4c, 0x82, 0x10, 0x65, 0x46, 0x02, 0xea, 0x7a, 0xbe, 0x90,
	0x92, 0x7b, 0xf1, 0x0e, 0x44, 0x0f, 0xe3, 0x1d, 0x77, 0x79, 0x91, 0x7a, 0xbe, 0xc3, 0x0e, 0xca,
	0x2c, 0x8c, 0xd0, 0x55, 0x38, 0x1a, 0x6b, 0x2f, 0x80, 0x45, 0xb0, 0x3a, 0x99, 0x9d, 0x6d, 0xd5,
	0xad, 0xa9, 0x0a, 0x2d, 0x16, 0x6e, 0xe1, 0x38, 0x8a, 0x1d, 0xb1, 0x88, 0x9f, 0xc0, 0xb9, 0xae,
	0xd4, 0x30, 0xe0, 0x7e, 0xc8, 0xd0, 0x2e, 0x1c, 0xdf, 0x17, 0x11, 0x91, 0x3d, 0x95, 0x59, 0xb2,
	0xfb, 0x1d, 0xdf, 0x96, 0xd9, 0xd9, 0x0b, 0xad, 0xba, 0x35, 0x2d, 0x3d, 0x64, 0x36, 0x76, 0x94,
	0x0c, 0x7e, 0x09, 0xa0, 0xd1, 0x61, 0x74, 0x27, 0x9f, 0xe7, 0x65, 0x3f, 0x0a, 0x35, 0xeb, 0xf5,
	0x2e, 0xbf, 0xc9, 0x3e, 0x4a, 0xe8, 0x1e, 0x84, 0xa7, 0x05, 0x58, 0x18, 0x11, 0x78, 0xcb, 0xb6,
	0xac, 0x96, 0x1d, 0x57, 0xcb, 0x96, 0x6d, 0xd3, 0x6c, 0x0f, 0xa8, 0xcb, 0x94, 0x8d, 0xd3, 0x91,
	0x89, 0x3f, 0x02, 0x78, 0xf9, 0x4c, 0x22, 0x55, 0x82, 0x47, 0x70, 0x82, 0xaa, 0xd8, 0x02, 0x58,
	0xfc, 0x6f, 0x75, 0x2a, 0x73, 0xad, 0x7f, 0x11, 0x94, 0x42, 0x76, 0xae, 0x55, 0xb7, 0x66, 0x25,
	0xbb, 0x16, 0xc0, 0x4e, 0x5b, 0x0b, 0xdd, 0x86, 0xa3, 0x01, 0x75, 0x99, 0x22, 0x5f, 0xf9, 0x2d,
	0xb9, 0xc4, 0x71, 0x44, 0x12, 0xbe, 0x0f, 0xe7, 0x05, 0xf3, 0x9e, 0x32, 0xd7, 0xf5, 0x23, 0x70,
	0x42, 0xf3, 0xa8, 0x0a, 0x76, 0x50, 0xe8, 0x15, 0xec, 0xb4, 0x37, 0xe1, 0x02, 0xbc, 0x98, 0x10,
	0x52, 0xc7, 0xde, 0x83, 0xff, 0x2b, 0x54, 0xd5, 0xfa, 0x01, 0x4f, 0x8d, 0x5a, 0x75, 0x6b, 0xa6,
	0xeb, 0xd4, 0xd8, 0xd1, 0x4a, 0xf8, 0x05, 0x80, 0x97, 0x84, 0xdd, 0xee, 0x33, 0x9f, 0x95, 0x92,
	0xcd, 0x5f, 0x86, 0x63, 0x3c, 0x8e, 0x2b, 0xf2, 0xf3, 0xad, 0xba, 0x75, 0x4e, 0x2a, 0x89, 0x30,
	0x76, 0xe4, 0xf2, 0x5f, 0xeb, 0xfc, 0x07, 0x7d, 0x17, 0x13, 0x34, 0xff, 0x70, 0xe3, 0x33, 0xef,
	0xc7, 0xe0, 0x98, 0x60, 0x46, 0x6f, 0x00, 0x1c, 0x97, 0x57, 0x16, 0x6d, 0xf4, 0xe7, 0xea, 0x7d,
	0x27, 0x18, 0x9b, 0x43, 0x64, 0x48, 0x7f, 0xbc, 0xf2, 0xfc, 0xcb, 0x8f, 0xd7, 0x23, 0x57, 0x90,
	0x75, 0xfa, 0xb6, 0xd2, 0x2f, 0x22, 0x39, 0x91, 0xa4, 0x1a, 0x07, 0x6b, 0xe8, 0x33, 0x80, 0x33,
	0xdd, 0xb3, 0x84, 0xb6, 0x07, 0xb6, 0x4b, 0xdc, 0x09, 0x63, 0xe7, 0x0f, 0x32, 0x15, 0x70, 0x46,
	0x00, 0xdf, 0x40, 0x6b, 0xbf, 0x04, 0xd6, 0x2d, 0x21, 0x55, 0x19, 0xa8, 0xa1, 0xb7, 0x00, 0x4e,
	0xe8, 0x51, 0x40, 0x99, 0x01, 0xbc, 0x13, 0x03, 0x68, 0x6c, 0x0d, 0x95, 0xa3, 0x48, 0x97, 0x04,
	0xa9, 0x89, 0xd2, 0xbd, 0xa4, 0x55, 0x1d, 0xa9, 0xa1, 0x4f, 0x00, 0x4e, 0x77, 0xdd, 0x54, 0x74,
	0x73, 0x00, 0xb3, 0xb3, 0x26, 0xcd, 0xd8, 0x1e, 0x3e, 0x51, 0xa1, 0x6e, 0x08, 0xd4, 0x35, 0xb4,
	0xda, 0x8b, 0x2a, 0x86, 0xb3, 0xa3, 0xa6, 0xe2, 0x7f, 0x2d, 0xbb, 0x7b, 0xfc, 0xdd, 0x4c, 0xbd,
	0x6b, 0x98, 0xa9, 0xe3, 0x86, 0x09, 0x4e, 0x1a, 0x26, 0xf8, 0xd6, 0x30, 0xc1, 0xab, 0xa6, 0x99,
	0x3a, 0x69, 0x9a, 0xa9, 0xaf, 0x4d, 0x33, 0xf5, 0x78, 0xdd, 0xf5, 0xa2, 0xa7, 0xe5, 0x9c, 0x9d,
	0xe7, 0x45, 0xe2, 0xf1, 0xc3, 0x75, 0xee, 0xb3, 0xb6, 0xfa, 0x3e, 0x49, 0x7e, 0x1d, 0x73, 0xe3,
	0xe2, 0x63, 0xb7, 0xf5, 0x33, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xfa, 0xb2, 0xf8, 0xa8, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Domain gets a starname's domain info.
	Domain(ctx context.Context, in *QueryDomainRequest, opts ...grpc.CallOption) (*QueryDomainResponse, error)
	// DomainAccounts gets accounts associated with a given domain.
	DomainAccounts(ctx context.Context, in *QueryDomainAccountsRequest, opts ...grpc.CallOption) (*QueryDomainAccountsResponse, error)
	// Starname gets accounts associated with a given domain.
	Starname(ctx context.Context, in *QueryStarnameRequest, opts ...grpc.CallOption) (*QueryStarnameResponse, error)
	// OwnerAccounts gets accounts associated with a given owner.
	OwnerAccounts(ctx context.Context, in *QueryOwnerAccountsRequest, opts ...grpc.CallOption) (*QueryOwnerAccountsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Domain(ctx context.Context, in *QueryDomainRequest, opts ...grpc.CallOption) (*QueryDomainResponse, error) {
	out := new(QueryDomainResponse)
	err := c.cc.Invoke(ctx, "/starnamed.x.starname.v1beta1.Query/Domain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DomainAccounts(ctx context.Context, in *QueryDomainAccountsRequest, opts ...grpc.CallOption) (*QueryDomainAccountsResponse, error) {
	out := new(QueryDomainAccountsResponse)
	err := c.cc.Invoke(ctx, "/starnamed.x.starname.v1beta1.Query/DomainAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Starname(ctx context.Context, in *QueryStarnameRequest, opts ...grpc.CallOption) (*QueryStarnameResponse, error) {
	out := new(QueryStarnameResponse)
	err := c.cc.Invoke(ctx, "/starnamed.x.starname.v1beta1.Query/Starname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OwnerAccounts(ctx context.Context, in *QueryOwnerAccountsRequest, opts ...grpc.CallOption) (*QueryOwnerAccountsResponse, error) {
	out := new(QueryOwnerAccountsResponse)
	err := c.cc.Invoke(ctx, "/starnamed.x.starname.v1beta1.Query/OwnerAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Domain gets a starname's domain info.
	Domain(context.Context, *QueryDomainRequest) (*QueryDomainResponse, error)
	// DomainAccounts gets accounts associated with a given domain.
	DomainAccounts(context.Context, *QueryDomainAccountsRequest) (*QueryDomainAccountsResponse, error)
	// Starname gets accounts associated with a given domain.
	Starname(context.Context, *QueryStarnameRequest) (*QueryStarnameResponse, error)
	// OwnerAccounts gets accounts associated with a given owner.
	OwnerAccounts(context.Context, *QueryOwnerAccountsRequest) (*QueryOwnerAccountsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Domain(ctx context.Context, req *QueryDomainRequest) (*QueryDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Domain not implemented")
}
func (*UnimplementedQueryServer) DomainAccounts(ctx context.Context, req *QueryDomainAccountsRequest) (*QueryDomainAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DomainAccounts not implemented")
}
func (*UnimplementedQueryServer) Starname(ctx context.Context, req *QueryStarnameRequest) (*QueryStarnameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Starname not implemented")
}
func (*UnimplementedQueryServer) OwnerAccounts(ctx context.Context, req *QueryOwnerAccountsRequest) (*QueryOwnerAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OwnerAccounts not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Domain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Domain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/starnamed.x.starname.v1beta1.Query/Domain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Domain(ctx, req.(*QueryDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DomainAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDomainAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DomainAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/starnamed.x.starname.v1beta1.Query/DomainAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DomainAccounts(ctx, req.(*QueryDomainAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Starname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStarnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Starname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/starnamed.x.starname.v1beta1.Query/Starname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Starname(ctx, req.(*QueryStarnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OwnerAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOwnerAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OwnerAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/starnamed.x.starname.v1beta1.Query/OwnerAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OwnerAccounts(ctx, req.(*QueryOwnerAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "starnamed.x.starname.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Domain",
			Handler:    _Query_Domain_Handler,
		},
		{
			MethodName: "DomainAccounts",
			Handler:    _Query_DomainAccounts_Handler,
		},
		{
			MethodName: "Starname",
			Handler:    _Query_Starname_Handler,
		},
		{
			MethodName: "OwnerAccounts",
			Handler:    _Query_OwnerAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "x/starname/types/query.proto",
}

func (m *QueryDomainRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDomainRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDomainRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDomainResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDomainResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDomainResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Domain != nil {
		{
			size, err := m.Domain.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDomainAccountsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDomainAccountsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDomainAccountsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDomainAccountsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDomainAccountsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDomainAccountsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Page != nil {
		{
			size, err := m.Page.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Accounts) > 0 {
		for iNdEx := len(m.Accounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Accounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryStarnameRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStarnameRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStarnameRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Starname) > 0 {
		i -= len(m.Starname)
		copy(dAtA[i:], m.Starname)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Starname)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryStarnameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStarnameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStarnameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Account != nil {
		{
			size, err := m.Account.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOwnerAccountsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOwnerAccountsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOwnerAccountsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOwnerAccountsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOwnerAccountsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOwnerAccountsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Page != nil {
		{
			size, err := m.Page.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Accounts) > 0 {
		for iNdEx := len(m.Accounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Accounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryDomainRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDomainResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Domain != nil {
		l = m.Domain.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDomainAccountsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDomainAccountsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Accounts) > 0 {
		for _, e := range m.Accounts {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Page != nil {
		l = m.Page.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryStarnameRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Starname)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryStarnameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Account != nil {
		l = m.Account.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryOwnerAccountsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryOwnerAccountsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Accounts) > 0 {
		for _, e := range m.Accounts {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Page != nil {
		l = m.Page.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryDomainRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDomainRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDomainRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDomainResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDomainResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDomainResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Domain == nil {
				m.Domain = &Domain{}
			}
			if err := m.Domain.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDomainAccountsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDomainAccountsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDomainAccountsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDomainAccountsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDomainAccountsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDomainAccountsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Accounts = append(m.Accounts, &Account{})
			if err := m.Accounts[len(m.Accounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Page == nil {
				m.Page = &query.PageResponse{}
			}
			if err := m.Page.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStarnameRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStarnameRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStarnameRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Starname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Starname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStarnameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStarnameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStarnameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Account == nil {
				m.Account = &Account{}
			}
			if err := m.Account.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOwnerAccountsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOwnerAccountsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOwnerAccountsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOwnerAccountsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOwnerAccountsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOwnerAccountsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Accounts = append(m.Accounts, &Account{})
			if err := m.Accounts[len(m.Accounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Page == nil {
				m.Page = &query.PageResponse{}
			}
			if err := m.Page.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
